export const LOADGENRESELECTLIST = 'LOADGENRESELECTLIST'
export const LOADGENRESELECTLIST_SUCCESS = 'LOADGENRESELECTLIST.SUCCESS'
export const RECENTLYREVIEWEDTOPPUBLICATIONS = 'RECENTLYREVIEWEDTOPPUBLICATIONS'
export const RECENTLYREVIEWEDTOPPUBLICATIONS_SUCCESS = 'RECENTLYREVIEWEDTOPPUBLICATIONS.SUCCESS'